# Generated by Django 4.1.6 on 2023-03-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_owner'),
        ('citizens', '0003_alter_citizen_first_name'),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='cadastre_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OwnerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateField()),
                ('cadastre_value_of_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('date_of_sale', models.DateField()),
                ('cadastre_value_of_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('owner_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_owner_com_h', to='companies.company')),
                ('owner_pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_owner_pp_h', to='citizens.citizen')),
                ('real_estate_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_object', to='real_estate.realestate')),
            ],
        ),
    ]
