# Generated by Django 4.1.6 on 2023-06-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_minecraftmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minecraftmap',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
