# Generated by Django 4.1.6 on 2023-03-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0003_alter_citizen_first_name'),
        ('companies', '0005_alter_company_owner'),
        ('real_estate', '0002_alter_realestate_cadastre_number_ownerhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnerHistory',
            new_name='RealEstateOwnerHistory',
        ),
    ]
