# Generated by Django 4.1.6 on 2023-03-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_rename_ownerhistory_realestateownerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateownerhistory',
            name='date_of_sale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
