# Generated by Django 4.1.6 on 2023-03-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_realestateownerhistory_date_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestatetypes',
            name='coef_of_cadastre_value',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=4),
            preserve_default=False,
        ),
    ]
