# Generated by Django 4.1.6 on 2023-02-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_alter_handlingunit_hu_alter_handlingunit_location_and_more'),
        ('companies', '0004_company_manufacturer_code'),
        ('warehouses', '0002_alter_warehouse_name_alter_warehouse_warehouse_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(default='WO00001', max_length=10)),
                ('date', models.DateField()),
                ('enviroment_tax_on_workorder_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_work_order', to='companies.company')),
                ('warehouse_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_warehouse', to='warehouses.warehouse')),
                ('warehouse_raw_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_warehouse', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItemRawMat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='products.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_mat_work_order', to='invoices.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItemProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_single_units', models.IntegerField(default=0)),
                ('qunatity_in_packages', models.IntegerField(default=0)),
                ('enviroment_tax_on_workorder', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='products.product')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_work_order', to='invoices.workorder')),
            ],
        ),
    ]
