# Generated by Django 4.1.6 on 2023-02-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderitemproduction',
            old_name='qunatity_in_packages',
            new_name='quantity_in_packages',
        ),
    ]
