# Generated by Django 4.1.6 on 2023-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_qunatity_in_packages_workorderitemproduction_quantity_in_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitemproduction',
            name='quantity_in_units',
            field=models.IntegerField(default=0),
        ),
    ]
