# Generated by Django 4.1.6 on 2023-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_workorderitemproduction_quantity_in_palets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderitemrawmat',
            old_name='quantity',
            new_name='quantity_in_packages',
        ),
        migrations.AddField(
            model_name='workorderitemrawmat',
            name='quantity_in_units',
            field=models.IntegerField(default=0),
        ),
    ]
