# Generated by Django 4.1.6 on 2023-02-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_warehouse_name_alter_warehouse_warehouse_code'),
        ('products', '0015_alter_handlingunit_tht_warning_date'),
        ('companies', '0004_company_manufacturer_code'),
        ('invoices', '0006_rename_quantity_workorderitemrawmat_quantity_in_packages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='AA00001', max_length=8)),
                ('date', models.DateField()),
                ('payment_term_options', models.CharField(choices=[('7', '7 days'), ('14', '14 days'), ('21', '21 day'), ('30', '30 days'), ('60', '60 days')], default='14', max_length=10)),
                ('payment_term', models.DateField(null=True)),
                ('invoice_paid', models.BooleanField()),
                ('invoice_paid_confirmed', models.BooleanField()),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('btw_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount_total_with_btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='companies.company')),
                ('customer_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_warehouse', to='warehouses.warehouse')),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplier', to='companies.company')),
                ('suplier_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplier_warehouse', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_units', models.IntegerField(default=0)),
                ('quantity_in_packages', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('lineitem_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lineitem_total_with_btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
