# Generated by Django 4.1.6 on 2023-02-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_transferorder_transferorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferorderitem',
            old_name='quantity',
            new_name='quantity_in_units',
        ),
    ]
