# Generated by Django 4.1.6 on 2023-02-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_owner'),
        ('products', '0016_handlingunit_company_alter_handlingunit_manufacturer'),
        ('citizens', '0003_alter_citizen_first_name'),
        ('warehouses', '0003_alter_warehouse_company'),
        ('invoices', '0010_rename_quantity_transferorderitem_quantity_in_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_sale_number', models.CharField(default='RT1', max_length=12)),
                ('date', models.DateField()),
                ('retail_sale_paid', models.BooleanField()),
                ('retail_sale_paid_confirmed', models.BooleanField()),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('btw_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount_total_with_btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='citizens.citizen')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='companies.company')),
                ('retailer_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_warehouse', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='RetailSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('retailitem_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('retailitem_total_with_btw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('retail_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailitems', to='invoices.retailsale')),
            ],
        ),
    ]
