# Generated by Django 4.1.6 on 2023-02-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_constructioninvoice_constructioninvoicelabourcosts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderitemproduction',
            old_name='quantity_in_packages',
            new_name='qty',
        ),
        migrations.RenameField(
            model_name='workorderitemrawmat',
            old_name='quantity_in_packages',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='workorderitemproduction',
            name='quantity_in_single_units',
        ),
        migrations.RemoveField(
            model_name='workorderitemproduction',
            name='quantity_in_units',
        ),
        migrations.RemoveField(
            model_name='workorderitemrawmat',
            name='quantity_in_units',
        ),
        migrations.AddField(
            model_name='workorderitemproduction',
            name='qty_in',
            field=models.CharField(choices=[('0', 'Units'), ('1', 'Packages'), ('2', 'Pallets')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='workorderitemrawmat',
            name='qty_in',
            field=models.CharField(choices=[('0', 'Units'), ('1', 'Packages'), ('2', 'Pallets')], default='0', max_length=10),
        ),
    ]
