# Generated by Django 4.1.6 on 2023-02-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_rename_quantity_in_packages_workorderitemproduction_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='quantity_in_packages',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity_in_units',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='qty_in',
            field=models.CharField(choices=[('0', 'Units'), ('1', 'Packages'), ('2', 'Pallets')], default='0', max_length=10),
        ),
    ]
