# Generated by Django 4.1.6 on 2023-02-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0003_alter_citizen_first_name'),
        ('companies', '0004_company_manufacturer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_number', models.CharField(default='MK84MKCB...', max_length=18, primary_key=True, serialize=False)),
                ('bank_account_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_account_owner_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_owner_com', to='companies.company')),
                ('bank_account_owner_pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_owner_pp', to='citizens.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('amount_plus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_minus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_entry', to='bank.bankaccount')),
            ],
        ),
    ]
