# Generated by Django 4.1.6 on 2023-02-18 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountentry',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 18, 17, 33, 33, 1731, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
