# Generated by Django 4.1.6 on 2023-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='first_name_display',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='last_name_display',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
