# Generated by Django 4.1.6 on 2023-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_alter_citizen_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='first_name',
            field=models.CharField(default=' ', max_length=254),
            preserve_default=False,
        ),
    ]
