# Generated by Django 4.1.6 on 2023-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('date', models.DateField()),
                ('report_type', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=16)),
                ('report_year', models.IntegerField()),
                ('report_month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('report_number', models.CharField(default=1, max_length=10, primary_key=True, serialize=False)),
                ('gpd_from_invoices', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gpd_from_retail', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gpd_from_construction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gpd_in_period', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
