# Generated by Django 4.1.6 on 2023-02-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_appsettings_iin_rate_appsettings_uin_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='vsaoi_dd',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='vsaoi_dn',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=4),
            preserve_default=False,
        ),
    ]
