# Generated by Django 4.1.6 on 2023-02-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appsettings_vsaoi_dd_appsettings_vsaoi_dn'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='btw',
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=8),
            preserve_default=False,
        ),
    ]
