# Generated by Django 4.1.6 on 2023-03-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appsettings_btw'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='base_cadaster_value',
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=4),
            preserve_default=False,
        ),
    ]
