# Generated by Django 4.1.6 on 2023-03-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appsettings_base_cadaster_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='base_cadaster_value',
            new_name='base_cadastre_value',
        ),
    ]
