# Generated by Django 4.1.6 on 2023-02-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citizens', '0003_alter_citizen_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, max_length=254)),
                ('warehouse', models.BooleanField(default=False)),
                ('registration_number', models.PositiveIntegerField(blank=True, default=1, primary_key=True, serialize=False)),
                ('invoice_prefix', models.CharField(max_length=2, unique=True)),
                ('street_adress_1', models.IntegerField(blank=True, default=0)),
                ('street_adress_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('post_code', models.CharField(blank=True, max_length=6)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('total_bruto_salaries', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_vsaoi_dd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_vsaoi_dn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_iin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_salary_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citizens.citizen')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=254, null=True)),
                ('salary_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_vsaoi_dd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_vsaoi_dn', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_iin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salary_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='companies.company')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='citizens.citizen')),
            ],
        ),
    ]
