# Generated by Django 4.1.6 on 2023-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_total_salaries_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
