# Generated by Django 4.1.6 on 2023-02-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_employee_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manufacturer_code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
