# Generated by Django 4.1.6 on 2023-02-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='AA001', max_length=7, unique=True)),
                ('name', models.CharField(default='name', max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('enviroment_tax_class', models.CharField(choices=[('0', 'No Tax'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4')], default='0', max_length=7)),
                ('enviroment_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('expiry_end_date_cat', models.CharField(choices=[('0', 'No End Date'), ('1', 'days'), ('2', 'weeks'), ('3', 'months'), ('4', 'years'), ('5', 'end of month + months')], default='0', max_length=7)),
                ('expiry_end_date_terms', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
