# Generated by Django 4.1.6 on 2023-02-09 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_expiry_end_date_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lay_per_palet',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='product',
            name='packages_per_lay',
            field=models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddField(
            model_name='product',
            name='packages_per_palet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_lay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_package',
            field=models.IntegerField(default=64, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)]),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_palet',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
