# Generated by Django 4.1.6 on 2023-02-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_employee_count'),
        ('products', '0004_product_paletizable'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('qty_units', models.CharField(choices=[('0', 'Units'), ('1', 'Packages')], default='0', max_length=7)),
                ('hu', models.IntegerField(default=0)),
                ('batch_nr', models.CharField(blank=True, max_length=9, null=True)),
                ('release_date', models.DateField()),
                ('tht', models.DateField()),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
