# Generated by Django 4.1.6 on 2023-02-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_warehouse_name_alter_warehouse_warehouse_code'),
        ('products', '0005_handlingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse'),
        ),
    ]
