# Generated by Django 4.1.6 on 2023-02-12 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_warehouse_name_alter_warehouse_warehouse_code'),
        ('products', '0006_handlingunit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingunit',
            name='hu',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='handlingunit',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='warehouses.warehouse'),
        ),
        migrations.AlterField(
            model_name='handlingunit',
            name='tht',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
