# Generated by Django 4.1.6 on 2023-02-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_handlingunit_hu_alter_handlingunit_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handlingunit',
            name='tht',
            field=models.DateField(),
        ),
    ]
