# Generated by Django 4.1.6 on 2023-02-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_handlingunit_tht'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingUnitMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doc_nr', models.CharField(default='0', max_length=20)),
                ('from_location', models.CharField(default='0', max_length=60)),
                ('to_location', models.CharField(default='0', max_length=60)),
                ('from_hu', models.CharField(default='', max_length=60)),
                ('to_hu', models.CharField(default='', max_length=60)),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_hu', to='products.handlingunit')),
            ],
        ),
    ]
