# Generated by Django 4.1.6 on 2023-02-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_handlingunitmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunitmovement',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
