# Generated by Django 4.1.6 on 2023-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_handlingunit_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handlingunit',
            name='empty',
        ),
        migrations.AddField(
            model_name='handlingunit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
