# Generated by Django 4.1.6 on 2023-02-16 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_handlingunit_empty_handlingunit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunit',
            name='tht_warning_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 16, 17, 56, 17, 402391, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
