# Generated by Django 4.1.6 on 2023-02-17 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_manufacturer_code'),
        ('products', '0015_alter_handlingunit_tht_warning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='handlingunit',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer', to='companies.company'),
        ),
    ]
