# Generated by Django 4.1.6 on 2023-02-24 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_owner'),
        ('products', '0016_handlingunit_company_alter_handlingunit_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlingunit',
            name='hu_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hu_issued_by', to='companies.company'),
        ),
    ]
